[build]
target = "riscv64imac-unknown-none-elf"
# [build]
# target = "riscv32imc-unknown-none-elf"

# 下面出现了链接问题，__atomic_load_8不知道哪里在使用
# 它需要保证开+a
# [unstable]
# build-std = ["core", "alloc", "compiler_builtins"]
# build-std-features = ["compiler-builtins-mem"]

# [build]
# target = "riscv64imc.json"
# rustflags = [
#   "-A",
#   "explicit_builtin_cfgs_in_flags",

#   "--cfg",
#   "portable_atomic_no_outline_atomics",

#   "-C",
#   "target-feature=+a",

#   "--cfg",
#   "target_has_atomic_load_store",
#   "--cfg",
#   'target_has_atomic_load_store="8"',
#   "--cfg",
#   'target_has_atomic_load_store="16"',
#   "--cfg",
#   'target_has_atomic_load_store="32"',
#   "--cfg",
#   'target_has_atomic_load_store="ptr"',

#   "--cfg",
#   "target_has_atomic",
#   "--cfg",
#   'target_has_atomic="8"',
#   "--cfg",
#   'target_has_atomic="16"',
#   "--cfg",
#   'target_has_atomic="32"',
#   "--cfg",
#   'target_has_atomic="ptr"',
# ]
