# {这一部分可用
[build]
target = "riscv64imac-unknown-none-elf" # 保持目标不变但覆盖特性

# [target.riscv64imac-unknown-none-elf]
# rustflags = [
#   "-Clink-args=-Tlinker.ld",
#   # "-C", "link-arg=-nostartfiles"
# ]
# }
# 针对自定义目标的编译参数
# [target.riscv64imac-unknown-none-elf]
# rustflags = [
#   "-C",
#   "link-arg=-Tlink.x",          # 强制使用链接脚本
#   "-C",
#   "link-arg=-nostartfiles",     # 禁用系统启动文件
#   "-C",
#   "link-arg=-Wl,--gc-sections", # 链接时消除未使用段
# ]


# 下面出现了链接问题，__atomic_load_8不知道哪里在使用
# 它需要保证开+a
# [unstable]
# build-std = ["core", "alloc", "compiler_builtins"]
# build-std-features = ["compiler-builtins-mem"]

# [build]
# target = "riscv64imc.json"


# # 针对自定义目标的编译参数
# [target.riscv64imc]
# rustflags = [
#   "-C",
#   "link-arg=-Tlink.x", # 强制使用链接脚本
#   # "-C",
#   # "link-arg=-nostartfiles",     # 禁用系统启动文件
#   # "-C",
#   # "target-feature=+m,+c",       # 启用乘法和压缩指令
#   # "-C",
#   # "link-arg=-Wl,--gc-sections", # 链接时消除未使用段
# ]
